bible_verses_about_life = [
    "Genesis 2:7 - Then the LORD God formed a man from the dust of the ground and breathed into his nostrils the breath of life, and the man became a living being.",
    "John 14:6 - Jesus answered, 'I am the way and the truth and the life. No one comes to the Father except through me.'",
    "Jeremiah 29:11 - For I know the plans I have for you, declares the LORD, plans for welfare and not for evil, to give you a future and a hope.",
    "Psalm 139:13-16 - For you formed my inward parts; you knitted me together in my mother's womb. I praise you, for I am fearfully and wonderfully made. Wonderful are your works; my soul knows it very well.",
    "Proverbs 3:5-6 - Trust in the LORD with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.",
    "John 10:10 - The thief comes only to steal and kill and destroy. I came that they may have life and have it abundantly.",
    "Romans 6:23 - For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord.",
    "Psalm 23:1-4 - The LORD is my shepherd; I shall not want. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul. He leads me in paths of righteousness for his name's sake. Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me; your rod and your staff, they comfort me.",
    "Matthew 11:28-30 - Come to me, all who labor and are heavy laden, and I will give you rest. Take my yoke upon you, and learn from me, for I am gentle and lowly in heart, and you will find rest for your souls. For my yoke is easy, and my burden is light.",
    "1 Corinthians 15:22 - For as in Adam all die, so also in Christ shall all be made alive.",
    "Psalm 16:11 - You make known to me the path of life; in your presence, there is fullness of joy; at your right hand are pleasures forevermore.",
    "Psalm 34:18 - The LORD is near to the brokenhearted and saves the crushed in spirit.",
    "Ephesians 2:10 - For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.",
    "Isaiah 41:10 - Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.",
    "Matthew 6:25-27 - Therefore I tell you, do not be anxious about your life, what you will eat or what you will drink, nor about your body, what you will put on. Is not life more than food, and the body more than clothing? Look at the birds of the air: they neither sow nor reap nor gather into barns, and yet your heavenly Father feeds them. Are you not of more value than they? And which of you by being anxious can add a single hour to his span of life?",
    "Philippians 4:13 - I can do all things through him who strengthens me.",
    "John 3:16 - For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.",
    "Psalm 119:50 - This is my comfort in my affliction, that your promise gives me life.",
    "Psalm 37:4 - Delight yourself in the LORD, and he will give you the desires of your heart.",
    "Romans 8:28 - And we know that in all things God works for the good of those who love him, who have been called according to his purpose.",
    "John 11:25 - Jesus said to her, 'I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live.'",
    "Jeremiah 17:7-8 - Blessed is the man who trusts in the LORD, whose trust is the LORD. He is like a tree planted by water, that sends out its roots by the stream, and does not fear when heat comes, for its leaves remain green, and is not anxious in the year of drought, for it does not cease to bear fruit.",
    "Psalm 71:20-21 - You who have made me see many troubles and calamities will revive me again; from the depths of the earth you will bring me up again. You will increase my greatness and comfort me again.",
    "John 6:35 - Jesus said to them, 'I am the bread of life; whoever comes to me shall not hunger, and whoever believes in me shall never thirst.'",
    "1 John 5:11 - And this is the testimony, that God gave us eternal life, and this life is in his Son.",
    "John 1:4 - In him was life, and the life was the light of men.",
    "Romans 12:2 - Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect.",
    "Psalm 27:1 - The LORD is my light and my salvation; whom shall I fear? The LORD is the stronghold of my life; of whom shall I be afraid?",
    "Proverbs 14:27 - The fear of the LORD is a fountain of life, that one may turn away from the snares of death.",
    "Psalm"
]

bible_verses_about_gods_love = [
    "John 3:16 - For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.",
    "Romans 8:38-39 - For I am sure that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers, nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord.",
    "1 John 4:8 - Anyone who does not love does not know God, because God is love.",
    "1 John 4:16 - So we have come to know and to believe the love that God has for us. God is love, and anyone who abides in love abides in God, and God abides in them.",
    "Romans 5:8 - But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.",
    "Ephesians 3:17-19 - so that Christ may dwell in your hearts through faith—that you, being rooted and grounded in love, may have strength to comprehend with all the saints what is the breadth and length and height and depth, and to know the love of Christ that surpasses knowledge, that you may be filled with all the fullness of God.",
    "Jeremiah 31:3 - The LORD appeared to him from far away. I have loved you with an everlasting love; therefore, I have continued to extend faithful love to you.",
    "Zephaniah 3:17 - The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.",
    "Psalm 136:26 - Give thanks to the God of heaven, for his steadfast love endures forever.",
    "Psalm 86:15 - But you, O Lord, are a God merciful and gracious, slow to anger and abounding in steadfast love and faithfulness.",
    "1 Corinthians 13:4-7 - Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs. Love does not delight in evil but rejoices with the truth. It always protects, always trusts, always hopes, always perseveres.",
    "Romans 8:39 - nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God in Christ Jesus our Lord.",
    "Psalm 103:8 - The LORD is merciful and gracious, slow to anger and abounding in steadfast love.",
    "Psalm 117:2 - For great is his steadfast love toward us, and the faithfulness of the LORD endures forever. Praise the LORD!",
    "1 John 4:7 - Beloved, let us love one another, for love is from God, and whoever loves has been born of God and knows God.",
    "John 15:9-10 - As the Father has loved me, so have I loved you. Abide in my love. If you keep my commandments, you will abide in my love, just as I have kept my Father's commandments and abide in his love.",
    "Romans 8:28 - And we know that for those who love God all things work together for good, for those who are called according to his purpose.",
    "Zephaniah 3:17 - The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.",
    "Ephesians 2:4-5 - But God, being rich in mercy, because of the great love with which he loved us, even when we were dead in our trespasses, made us alive together with Christ—by grace you have been saved.",
    "1 John 4:19 - We love because he first loved us.",
    "Psalm 33:5 - He loves righteousness and justice; the earth is full of the steadfast love of the LORD.",
    "Deuteronomy 7:9 - Know therefore that the LORD your God is God, the faithful God who keeps covenant and steadfast love with those who love him and keep his commandments, to a thousand generations.",
    "Ephesians 5:2 - And walk in love, as Christ loved us and gave himself up for us, a fragrant offering and sacrifice to God.",
    "1 John 3:1 - See what kind of love the Father has given to us, that we should be called children of God; and so we are. The reason why the world does not know us is that it did not know him.",
    "Psalm 63:3 - Because your steadfast love is better than life, my lips will praise you.",
]

bible_verses_about_working_hard = [
    "Colossians 3:23 - Whatever you do, work heartily, as for the Lord and not for men.",
    "Proverbs 14:23 - In all toil there is profit, but mere talk tends only to poverty.",
    "Ecclesiastes 9:10 - Whatever your hand finds to do, do it with your might, for there is no work or thought or knowledge or wisdom in Sheol, to which you are going.",
    "2 Thessalonians 3:10 - For even when we were with you, we would give you this command: If anyone is not willing to work, let him not eat.",
    "Proverbs 12:11 - Whoever works his land will have plenty of bread, but he who follows worthless pursuits lacks sense.",
    "Proverbs 6:6-8 - Go to the ant, O sluggard; consider her ways, and be wise. Without having any chief, officer, or ruler, she prepares her bread in summer and gathers her food in harvest.",
    "Proverbs 13:4 - The soul of the sluggard craves and gets nothing, while the soul of the diligent is richly supplied.",
    "1 Corinthians 15:58 - Therefore, my beloved brothers, be steadfast, immovable, always abounding in the work of the Lord, knowing that in the Lord your labor is not in vain.",
    "Proverbs 10:4 - A slack hand causes poverty, but the hand of the diligent makes rich.",
    "Proverbs 21:5 - The plans of the diligent lead surely to abundance, but everyone who is hasty comes only to poverty.",
    "Ephesians 4:28 - Let the thief no longer steal, but rather let him labor, doing honest work with his own hands, so that he may have something to share with anyone in need.",
    "1 Timothy 5:8 - But if anyone does not provide for his relatives, and especially for members of his household, he has denied the faith and is worse than an unbeliever.",
    "Proverbs 22:29 - Do you see a man skillful in his work? He will stand before kings; he will not stand before obscure men.",
    "1 Thessalonians 4:11 - and to aspire to live quietly, and to mind your own affairs, and to work with your hands, as we instructed you,",
    "Proverbs 16:3 - Commit your work to the Lord, and your plans will be established.",
    "Proverbs 24:30-34 - I passed by the field of a sluggard, by the vineyard of a man lacking sense, and behold, it was all overgrown with thorns; the ground was covered with nettles, and its stone wall was broken down. Then I saw and considered it; I looked and received instruction. A little sleep, a little slumber, a little folding of the hands to rest, and poverty will come upon you like a robber, and want like an armed man.",
    "2 Timothy 2:15 - Do your best to present yourself to God as one approved, a worker who has no need to be ashamed, rightly handling the word of truth.",
    "Proverbs 19:15 - Slothfulness casts into a deep sleep, and an idle person will suffer hunger.",
    "Genesis 2:15 - The Lord God took the man and put him in the garden of Eden to work it and keep it.",
    "2 Thessalonians 3:13 - As for you, brothers, do not grow weary in doing good.",
    "Romans 12:11 - Do not be slothful in zeal, be fervent in spirit, serve the Lord.",
    "Proverbs 24:27 - Prepare your work outside; get everything ready for yourself in the field, and after that build your house.",
    "Luke 10:7 - And remain in the same house, eating and drinking what they provide, for the laborer deserves his wages. Do not go from house to house.",
    "Matthew 5:16 - In the same way, let your light shine before others, so that they may see your good works and give glory to your Father who is in heaven.",
    "1 Corinthians 9:24 - Do you not know that in a race all the runners run, but only one receives the prize? So run that you may obtain it.",
    "Philippians 2:14-16 - Do all things without grumbling or disputing, that you may be blameless and innocent, children of God without blemish in the midst of a crooked and twisted generation, among whom you shine as lights in the world, holding fast to the word of life, so that in the day of Christ I may be proud that I did not run in vain or labor in vain.",
    "Romans 12:6 - Having gifts that differ according to the grace given to us, let us use them: if prophecy, in proportion to our faith; if service, in our serving; the one who teaches, in his teaching;",
    "Proverbs 13:11 - Wealth gained hastily will dwindle, but whoever gathers little by little will increase it.",
    "Philippians 4:13 - I can do all things through him who strengthens me.",
    "Proverbs 14:23 - In all toil there is profit, but mere talk tends only to poverty.",
    "Proverbs 28:19 - Whoever works his land will have plenty of bread, but he who follows worthless pursuits will have plenty of poverty.",
    "1 Thessalonians 5:16-18 - Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you.",
    "Proverbs 10:5 - He who gathers in summer is a prudent son, but he who sleeps in harvest is a son who brings shame.",
    "1 Corinthians 10:31 - So, whether you eat or drink, or whatever you do, do all to the glory of God.",
    "Galatians 6:9 - And let us not grow weary of doing good, for in due season we will reap, if we do not give up.",
    "Proverbs 12:24 - The hand of the diligent will rule, while the slothful will be put to forced labor.",
    "2 Timothy 3:16-17 - All Scripture is breathed out by God and profitable for teaching, for reproof, for correction, and for training in righteousness, that the man of God may be complete, equipped for every good work.",
    "Matthew 6:33 - But seek first the kingdom of God and his righteousness, and all these things will be added to you.",
    "Proverbs 13:4 - The soul of the sluggard craves and gets nothing, while the soul of the diligent is richly supplied.",
    "Proverbs 20:4 - The sluggard does not plow in the autumn; he will seek at harvest and have nothing.",
    "1 Timothy 4:15 - Practice these things, immerse yourself in them, so that all may see your progress"
]


